### ISSUE TITLE
rss.p.theconnman.com is down

### ISSUE THREAD

**Issue by jsaalfeld** [TheConnMan/docker-hub-rss#12]
I stumbled upon this project while I was looking for a way to keep the software we use up to date. I used the service you provided at [your website](https://rss.p.theconnman.com/#?user=TheConnMan&repo=docker-hub-rss) to keep track of the versions and it is really helpful! But it seems to be down for a couple of days. Do you plan to bring it back up?

After an hour or so, I got some results displayed, but the page still seems to be down.

**Comment by TheConnMan** [comment]
Hi @jsaalfeld, I'm glad this project can help you!

I've had issues hosting that link as I host a lot of other stuff on that server and haven't had the time to maintain in. Yesterday I moved rss.p.theconnman.com to https://zeit.co/ so it's working at https://docker-hub-rss.now.sh/. The old link redirects, too, so you can use either.

**Comment by zhangyoufu** [comment]
@TheConnMan I think the redirection is not working properly. For example, `https://rss.p.theconnman.com/minio/minio.atom?includeRegex=%5ERELEASE%5C.` is redirected to `https://docker-hub-rss.now.sh/minio/minio.atom`, parameters are ignored.

**Comment by TheConnMan** [comment]
I see, you are correct. In that case I recommend you use the new URL directly. rss.p.thecoonman.com provides a 301 redirect to the new URL which is where the query params are getting dropped.
