### ISSUE TITLE
How to get a feed of the official feed?

### ISSUE THREAD

**Issue by Baklap4** [TheConnMan/docker-hub-rss#14]
Currently you have to specify a user and a repository to get a feed however offical repo's like rabbitmq don't have a user.. so how would we be able to add those feeds?

![image](https://user-images.githubusercontent.com/3918517/79216475-83f9f700-7e4d-11ea-933b-06164d2bfbe7.png)

**Comment by Baklap4** [comment]
The user should be `_` for official repo's like rabbitmq.

**Comment by TheConnMan** [comment]
Yeah, good question. Thanks for figuring out on your own and closing.

If you'd like to go one step further you could push a PR with a note on this in the docs or in the UI.

**Comment by Baklap4** [comment]
Will do 👍
