### ISSUE TITLE
Service at docker-hub-rss.theconnman.vercel.app/ is down

### ISSUE THREAD

**Issue by jsaalfeld** [TheConnMan/docker-hub-rss#21]
It seems, that your hosted Service at docker-hub-rss.theconnman.vercel.app/ is since one or two weeks. It would be really nice if it came back.

**Comment by TheConnMan** [comment]
It's hosted on Vercel and they've said it has too much traffic for the free tier. I'm working with them to get it back online.

**Comment by TheConnMan** [comment]
@jsaalfeld the site is back up.

**Comment by jsaalfeld** [comment]
Same issue again?

**Comment by TheConnMan** [comment]
Yes. I'll take a look this weekend.

**Comment by TheConnMan** [comment]
@jsaalfeld it's back up. I didn't get contacted by Vercel again, there's got to be an automated disablement on their side. I worked with them to get under the free tier limit, yet here we are. Sorry about the downtime.
