### ISSUE TITLE
Dockerfile without root permissions in runtime

### ISSUE THREAD

**Issue by JuniorJPDJ** [TheConnMan/docker-hub-rss#24]
Hi!
Your Dockerfile seems to use root user in runtime, that's not safe :<
Could you guys please fix this?

**Comment by TheConnMan** [comment]
@JuniorJPDJ do you have a recommendation on what change I should make?

**Comment by JuniorJPDJ** [comment]
You probably should play with files permissions and set [USER](https://docs.docker.com/engine/reference/builder/#user) inside Dockerfile.

**Comment by TheConnMan** [comment]
Would you be willing to push a PR to help with the fix? I'll gladly review and merge it in.

**Comment by JuniorJPDJ** [comment]
I did ;)
