### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com?

### ISSUE THREAD

**Issue by PeterDaveHello** [TheConnMan/docker-hub-rss#29]
https://travis-ci.org/TheConnMan/docker-hub-rss

>  Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

BTW, this project is really helpful 👍

**Comment by TheConnMan** [comment]
Hello, thanks for the note. I haven't been as diligent here as I should be (wrong year for me to be commenting, but close to the right month). I'll work to fix this.

**Comment by PeterDaveHello** [comment]
Good to know that 🎉

**Comment by TheConnMan** [comment]
Hey folks, I gave this a shot and am having a bit of trouble. If anyone has experience with this transition I could use the help, otherwise I'll give it another try soon.

**Comment by PeterDaveHello** [comment]
@TheConnMan I might be able to help, but will need some administration permission, not sure if it's good to you, can take some time to think about it, and I believe that the permission can be removed once the migration is done.

**Comment by TheConnMan** [comment]
Thanks for the offer, @PeterDaveHello! #44 might supersede this by converting the project to GitHub Actions. Let me run that down before coming back to this.

**Comment by TheConnMan** [comment]
Solved through https://github.com/TheConnMan/docker-hub-rss/pull/44!
