### ISSUE TITLE
Expose port 80 in container in order to increase compatibility with RSS aggregators

### ISSUE THREAD

**Issue by jmechnich** [TheConnMan/docker-hub-rss#31]
Hi! Let me start with thanking you for creating this extremely useful piece of software.

In my setup, I have added this container to the docker-compose file for deploying [tt-rss](https://tt-rss.org/).
By running the container in the same network as the RSS reader software, I don't have to expose the port to the host network at all.
However, tt-rss only works with the standard ports 80 and 443 for http and https, respectively.
There seems to be a good reason for that (see https://community.tt-rss.org/t/problem-subscribing-to-feed-on-custom-port/4203), so I am not expecting any changes on that end, and possibly there are comparable issues with other clients.

In my fork at https://github.com/jmechnich/docker-hub-rss, I have changed the port from 3000 to 80 and adapted the README accordingly, so that in practice, docker-hub-rss can still be used as before when running standalone (or using a reverse proxy or localtunnel).

I would be happy to open a PR here but first wanted to "test the waters" if this is something that might be considered useful.

**Comment by jmechnich** [comment]
Any opinions on this? :)

**Comment by TheConnMan** [comment]
@jmechnich sorry for the delay. I get that the internal port matters sometimes. What about splitting the difference: parameterize the port Docker Hub RSS _runs_ on, so if you want to change that port and call to it between containers you can, but don't change the default exposed port from the container to the outside world?

**Comment by jmechnich** [comment]
Fair enough, I have created a PR.

**Comment by TheConnMan** [comment]
Thanks! I commented on it.

**Comment by TheConnMan** [comment]
Merged and released!
