### ISSUE TITLE
High CPU and RAM usage

### ISSUE THREAD

**Issue by Marcus-Schubert** [TheConnMan/docker-hub-rss#38]
Hey there,

I'm using the latest docker image and run into a strange behavior. After the container is running for a few minutes, the consumed ressources are going up. So, the glances is showing me, that the container uses 1/3 of the available CPU and roughly 1GB of RAM.

This seems to be very high for "just" an RSS service.

When freshly restarted, the container consumes only very little ressources (< 1% CPU, 60MB RAM).

**Comment by sdellenb** [comment]
I can confirm this happening on my system since June 29. It appears to be the node process.

CPU, RAM and even network traffic rises for about a day and then I started getting alerts due to high system load. Restarting only solves it temporarily.

The Web UI with default settings always ends in an error (timeout).

**Edit: I've locally merged #37 and rebuilt and the issue is gone.**

**Comment by Marcus-Schubert** [comment]
Awesome, thank you for the quick response :pray:

**Comment by TheConnMan** [comment]
Hi all, I've merged #37. Please see if the issue is resolved and I'll close the ticket. Thanks!

**Comment by amatriain** [comment]
Does latest theconnman/docker-hub-rss image from docker hub include #37 ? I tried it but I got the same behavior (lots of requests to docker hub until API limit is reached, not immediately after deployment but about an hour later). I forked this project and manually merged #37, and my fork does not have this problem, this makes me think the docker hub image dos not have the fix.

**Comment by TheConnMan** [comment]
`latest` on Docker Hub should include the fix, yes. I will double-check this weekend, though.

**Comment by Marcus-Schubert** [comment]
I pulled the latest image from Docker Hub and have it running for quite some time now and no issues regarding CPU and RAM usage so far.

**Comment by amatriain** [comment]
Maybe I made a mistake updating the stack. I'm running the official image again and no issues for the moment. Sorry for the confusion.

**Comment by TheConnMan** [comment]
No worries, that means less work for me. I'll close this ticket.
