### ISSUE TITLE
Unavailability of https://docker-hub-rss.ezhub.de/ ?

### ISSUE THREAD

**Issue by drupol** [TheConnMan/docker-hub-rss#39]
Hello,

I open this issue just to let you know that the app hosted on https://docker-hub-rss.ezhub.de/ doesn't seems to work anymore since a couple of days.

Do you plan to restore it?

**Comment by TheConnMan** [comment]
@drupol sorry, I'm not affiliated with that domain. That must be someone else hosting this project on their own site.
