### ISSUE TITLE
Unable to create rss for ASP.NET Core Runtime

### ISSUE THREAD

**Issue by tvbishan** [TheConnMan/docker-hub-rss#46]
I have tried to create a rss feed for **https://hub.docker.com/_/microsoft-dotnet-aspnet** using **http://docker-hub-rss.theconnman.com/**. But it is not working. Am I doing it wrong?

![image](https://user-images.githubusercontent.com/12027448/203696305-9ce4d06c-2e8d-40ab-9160-6f89a4416acb.png)

**Comment by Skybladev2** [comment]
Just tried the same exact repo and no luck.

**Comment by TheConnMan** [comment]
Hey @tvbishan, these images are not hosted on Docker Hub, which is why they're not showing up. The images are hosted at mcr.microsoft.com, which this project doesn't support.
