### ISSUE TITLE
url not working for MS Teams RSS Connector

### ISSUE THREAD

**Issue by MSandro** [TheConnMan/docker-hub-rss#47]
Hello I would like to get Notifications via the Teams RSS Connector.
But it seems to not work with the .atom format.
Any idea what I could do?

**Comment by MSandro** [comment]
providing the feed as xml might work.
is there any container alternative which is doing this?

**Comment by MSandro** [comment]
sorry it was my mistake, I've hosted the container in the internal network :D

**Comment by TheConnMan** [comment]
Ha, no worries. @MSandro does that mean we can close this?
