### ISSUE TITLE
how to determine running version?

### ISSUE THREAD

**Issue by mortee** [TheConnMan/docker-hub-rss#48]
I'm running this in docker, and I'm wondering what's a reliable way to determine the exact version currently running? Either an endpoint, a command to be run in the container or similar possibility welcome.

**Comment by TheConnMan** [comment]
How about an `/info` endpoint which returns JSON, including the version?

**Comment by mortee** [comment]
Currently I can only try this on my mobile, but the `/info` endpoint returns this:
```
Cannot GET /info
```
Also, I don't know if the web framework is supposed to automatically serve it, but I couldn't find anything like that in the d-h-rss code itself.

In the meantime, I worked around it by extracting the version from package.json, but it seems to be a bit hackish...

**Comment by TheConnMan** [comment]
Sorry, I meant either you or I would implement that as a new endpoint. The endpoint doesn't exist yet.

**Comment by mortee** [comment]
Sure, it would make sense.

**Comment by mortee** [comment]
Ha ha, sorry about the confusion yesterday. I was on mobile, seeing just the notification emails about your comments, where the sender was displayed as your real name (as opposed to your nickname shown here), so initially I didn't make the connection that this was the author of d-h-rss 😃

**Comment by TheConnMan** [comment]
Ha, no worries. Check out #49. Is there anything else you can think of which may be helpful in an info endpoint?

**Comment by mortee** [comment]
This went over my head _again_. No, I guess that's pretty much it. Thanks for the quick reaction! 😃
