### ISSUE TITLE
Include or exclude by regex or glob

### ISSUE THREAD

**Issue by bootc** [TheConnMan/docker-hub-rss#7]
It would be great to be able to filter or exclude tags by pattern. Some images have a tag per Git commit which gets old very quickly, or several variants of `snapshot`, `latest` for different flavours and branches. I'd like to, for example, include only 'v*' or similar tags that match released versions.

**Comment by TheConnMan** [comment]
I like it. This is now live in the `dev` branch.

**Comment by bootc** [comment]
Thank you!
