### ISSUE TITLE
Some tags are not found

### ISSUE THREAD

**Issue by t3easy** [TheConnMan/docker-hub-rss#9]
If I e.g. search for php:7.3-fpm-alpine noting is foud
https://rss.p.theconnman.com/library/php.atom?include=7.3-fpm-alpine
but the tag exists.
Maybe a problem with the large number of current tags of php?

**Comment by TheConnMan** [comment]
Yes, that's the case. Docker Hub RSS only fetches a single page of tags ([default of 100](https://github.com/RyanTheAllmighty/Docker-Hub-API/blob/6856e3601df26ac89ecf17920d5ec5d724533e4f/src/api.js#L961)) so we'd need to paginate through more pages to fetch all tags.
